import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import Link from "next/link";
import Script from "next/script";
import Topbar from "../components/Topbar";
import Aside from "../components/Aside";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Hire Managment App",
  description: "Generated by create next app",
};

export default function Layout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
   
<>
  
  <div>
    <div className="wrapper">
      
      <Topbar></Topbar>
      
      <Aside></Aside>
      
      <main role="main" className="main-content">
       <div className="container-fluid">
        {children}
       </div>
       
      </main> 
    </div> 
 


   
  </div>
</>
  );
}
