apiVersion: v1
kind: Secret
metadata:
  name: api-gateway-secret
  namespace: hrmanagement

type: Opaque

stringData:
  REDIS_PASSWORD: "cantremember"
  INTERNAL_API_KEY: "super-secret-internal-key-123"
  ACCESS_TOKEN_SECRET:  "gj2+*bYxT0u2-^$#!.bfIUk1+:q{:8|<"
  REFRESH_TOKEN_SECRET: "VDWj;293quMn|*.p-&e>=%pb^A#_#vej"