apiVersion: apps/v1
kind: Deployment

metadata:
  name: job-service
  namespace: hrmanagement

spec:
  replicas: 3

  selector:
    matchLabels:
      app: job-service

  template:
    metadata:
      labels:
        app: job-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: job-service

          image: ghcr.io/ahmetkar/hrmanagement-job-service:v1.0.0

          imagePullPolicy: Always

          ports:
            - containerPort: 3331

          envFrom:
            - configMapRef:
                name: job-service-config

            - secretRef:
                name: job-service-secret