apiVersion: argoproj.io/v1alpha1
kind: Application

metadata:
  name: auth-service
  namespace: argocd

spec:
  project: hrmanagement

  source:
    repoURL: https://github.com/ahmetkar/Hire-Management-App.git
    targetRevision: main
    path: backend/hrmanagement/k8s/overlays/local/auth-service

  destination:
    server: https://kubernetes.default.svc
    namespace: hrmanagement

  syncPolicy:
    automated:
      prune: true
      selfHeal: true

    syncOptions:
      - CreateNamespace=true
      - PrunePropagationPolicy=foreground
      - PruneLast=true

  revisionHistoryLimit: 10