apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

resources:
  - api-gateway.yaml
  - auth-service.yaml
  - job-service.yaml
  - staff-service.yaml
  - management-service.yaml
  - ai-service.yaml