apiVersion: v1
kind: ConfigMap
metadata:
  name: api-gateway-config
  namespace: hrmanagement

data:
  PORT: "4000"
  AUTH_SERVICE_URL: "http://auth-service:3330"
  JOB_SERVICE_URL: "http://job-service:3331"
  MANAGEMENT_SERVICE_URL: "http://management-service:3332"
  STAFF_SERVICE_URL: "http://staff-service:3333"
  AI_SERVICE_URL: "http://ai-service:3334"
  CLIENT_URL: "http://localhost:3000"
  REDIS_PORT: "6379"
  REDIS_HOST: "redis"
  PROCESS_NAME: "api-gateway"
  KAFKA_BROKER: "kafka-kafka-bootstrap.kafka:9092"
  DATABASE_URL: "mongodb://mongodb:27017/hrmanagement?replicaSet=rs0"
  

 
  