apiVersion: apps/v1
kind: Deployment

metadata:
  name: ai-service
  namespace: hrmanagement

spec:
  replicas: 3

  selector:
    matchLabels:
      app: ai-service

  template:
    metadata:
      labels:
        app: ai-service
    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: ai-service

          image: ghcr.io/ahmetkar/hrmanagement-ai-service:latest

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "200m"
              memory: "512Mi"

            limits:
              cpu: "500m"
              memory: "1Gi"   
              
          ports:
            - containerPort: 3334

          envFrom:
            - configMapRef:
                name: ai-service-config

            - secretRef:
                name: ai-service-secret
          startupProbe:
            tcpSocket:
              port: 3334
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 3334
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 3334
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3