apiVersion: apps/v1
kind: Deployment

metadata:
  name: management-service
  namespace: hrmanagement

spec:
  replicas: 1

  selector:
    matchLabels:
      app: management-service

  template:
    metadata:
      labels:
        app: management-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: management-service

          image: ghcr.io/ahmetkar/hrmanagement-management-service:latest

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "100m"
              memory: "128Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 3332


          envFrom:
            - configMapRef:
                name: management-service-config

            - secretRef:
                name: management-service-secret
          startupProbe:
            tcpSocket:
              port: 3332
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 3332
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 3332
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3