apiVersion: apps/v1
kind: Deployment

metadata:
  name: redis
  namespace: hrmanagement

spec:
  replicas: 1

  selector:
    matchLabels:
      app: redis

  template:
    metadata:
      labels:
        app: redis

    spec:
      containers:
        - name: redis

          image: redis/redis-stack:latest
          imagePullPolicy: IfNotPresent

          ports:
            - containerPort: 6379
            - containerPort: 8001

          volumeMounts:
            - name: redis-data
              mountPath: /data

          livenessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 15
            periodSeconds: 10

          readinessProbe:
            tcpSocket:
              port: 6379
            initialDelaySeconds: 5
            periodSeconds: 5

          resources:
            requests:
              cpu: 100m
              memory: 256Mi

            limits:
              cpu: "1"
              memory: 1Gi

      volumes:
        - name: redis-data
          persistentVolumeClaim:
            claimName: redis-pvc