apiVersion: v1
kind: ConfigMap

metadata:
  name: staff-service-config
  namespace: hrmanagement

data:
  REDIS_PORT: "6379"
  REDIS_HOST: "redis"
  PROCESS_NAME: "staff-service"
  PORT: "3333"
  KAFKA_BROKER: "kafka-kafka-bootstrap.kafka:9092"
  CLIENT_URL: "http://localhost:3000"
  DATABASE_URL: "mongodb://mongodb:27017/hrmanagement?replicaSet=rs0"

