apiVersion: apps/v1
kind: Deployment

metadata:
  name: staff-service
  namespace: hrmanagement

spec:
  replicas: 2

  selector:
    matchLabels:
      app: staff-service

  template:
    metadata:
      labels:
        app: staff-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: staff-service

          image: ghcr.io/ahmetkar/hrmanagement-staff-service:latest

          imagePullPolicy: Always

          resources:
            requests:
              cpu: "250m"
              memory: "256Mi"

            limits:
              cpu: "500m"
              memory: "512Mi"

          ports:
            - containerPort: 3333

          envFrom:
            - configMapRef:
                name: staff-service-config

            - secretRef:
                name: staff-service-secret
          startupProbe:
            tcpSocket:
              port: 3333
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 3333
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 3333
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3
