import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";


import Script from "next/script";
import Body from "./components/Body";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Company Name - Job Application Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  
  return (
  
<html suppressHydrationWarning>
   <head suppressHydrationWarning>

  
    <link rel="stylesheet" href="/css/simplebar.css" />
   
    <link href="https://fonts.googleapis.com/css2?family=Overpass:ital,wght@0,100;0,200;0,300;0,400;0,600;0,700;0,800;0,900;1,100;1,200;1,300;1,400;1,600;1,700;1,800;1,900&display=swap" rel="stylesheet" />
   
    <link rel="stylesheet" href="/css/feather.css" />
    <link rel="stylesheet" href="/css/select2.css" />
    <link rel="stylesheet" href="/css/dropzone.css" />
    <link rel="stylesheet" href="/css/uppy.min.css" />
    <link rel="stylesheet" href="/css/jquery.steps.css" />
    <link rel="stylesheet" href="/css/jquery.timepicker.css" />
    <link rel="stylesheet" href="/css/quill.snow.css" />
    
    <link rel="stylesheet" href="/css/daterangepicker.css" />
  
    <link rel="stylesheet" href="/css/app-light.css" id="lightTheme" />
    <link rel="stylesheet" href="/css/app-dark.css" id="darkTheme" /> 
    
   
  </head>
    
    <Body children={children}></Body>
  

    <Script src="/js/jquery.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/popper.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/moment.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/bootstrap.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/simplebar.min.js" strategy="afterInteractive"></Script>
    <Script src='/js/daterangepicker.js' strategy="afterInteractive"></Script>
    <Script src='/js/jquery.stickOnScroll.js' strategy="afterInteractive"></Script>
    <Script src="/js/tinycolor-min.js" strategy="afterInteractive"></Script>
    <Script src="/js/config.js" strategy="afterInteractive"></Script>
    <Script src="/js/d3.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/topojson.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/datamaps.all.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/datamaps-zoomto.js" strategy="afterInteractive"></Script>
    <Script src="/js/datamaps.custom.js" strategy="afterInteractive"></Script>
    <Script src="/js/Chart.min.js" strategy="afterInteractive"></Script>
   <Script src="/js/chartdefault.js" strategy="afterInteractive"></Script>
    <Script src="/js/gauge.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/jquery.sparkline.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/apexcharts.min.js" strategy="afterInteractive"></Script>
    <Script src="/js/apexcharts.custom.js" strategy="afterInteractive"></Script>
    <Script src='/js/jquery.mask.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/select2.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/jquery.steps.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/jquery.validate.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/jquery.timepicker.js' strategy="afterInteractive"></Script>
    <Script src='/js/dropzone.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/uppy.min.js' strategy="afterInteractive"></Script>
    <Script src='/js/quill.min.js' strategy="afterInteractive"></Script>
   <Script src='/js/select2.js' strategy="afterInteractive"></Script>
    <Script src='/js/uppy.js' strategy="afterInteractive"></Script>
    <Script src="/js/apps.js" strategy="afterInteractive"></Script>

    <Script async src="https://www.googletagmanager.com/gtag/js?id=UA-56159088-1" strategy="afterInteractive"></Script>
    <Script src="/js/gtaghelper.js" strategy="afterInteractive"></Script>
  </html>
  
  );
}
