services:

  auth-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: auth-service
    env_file:
      - ./apps/auth-service/.env.production

  staff-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: staff-service
    env_file:
      - ./apps/staff-service/.env.production

  job-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: job-service
    env_file:
      - ./apps/job-service/.env.production

  management-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: management-service
    env_file:
      - ./apps/management-service/.env.production

  ai-service:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: ai-service
    env_file:
      - ./apps/ai-service/.env.production

  api-gateway:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        APP_NAME: api-gateway
    env_file:
      - ./apps/api-gateway/.env.production