apiVersion: apps/v1
kind: Deployment

metadata:
  name: auth-service
  namespace: hrmanagement

spec:
  replicas: 1

  selector:
    matchLabels:
      app: auth-service

  template:
    metadata:
      labels:
        app: auth-service

    spec:
      imagePullSecrets:
        - name: ghcr-secret

      containers:
        - name: auth-service

          image: ghcr.io/ahmetkar/hrmanagement-auth-service:v1.0.0

          imagePullPolicy: Always

          ports:
            - containerPort: 3330

          envFrom:
            - configMapRef:
                name: auth-service-config

            - secretRef:
                name: auth-service-secret
          startupProbe:
            tcpSocket:
              port: 3330
            periodSeconds: 10
            failureThreshold: 30

          readinessProbe:
            tcpSocket:
              port: 3330
            initialDelaySeconds: 20
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3

          livenessProbe:
            tcpSocket:
              port: 3330
            initialDelaySeconds: 60
            periodSeconds: 20
            timeoutSeconds: 5
            failureThreshold: 3