import type { Metadata } from "next";
import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";

import Script from "next/script";


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Company Name - Job Application Site",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
<>
 
  <div>
    <div className="wrapper">
      <nav className="navbar navbar-expand-lg navbar-light bg-white flex-row border-bottom shadow">
        <div className="container-fluid">
          <a className="navbar-brand mx-lg-1 mr-0" href="./index.html">
            <svg version="1.1" id="logo" className="navbar-brand-img brand-sm" xmlns="http://www.w3.org/2000/svg" xmlnsXlink="http://www.w3.org/1999/xlink" x="0px" y="0px" viewBox="0 0 120 120" xmlSpace="preserve">
              <g>
                <polygon className="st0" points="78,105 15,105 24,87 87,87 	" />
                <polygon className="st0" points="96,69 33,69 42,51 105,51 	" />
                <polygon className="st0" points="78,33 15,33 24,15 87,15 	" />
              </g>
            </svg>
          </a>
          <button className="navbar-toggler mt-2 mr-auto toggle-sidebar text-muted">
            <i className="fe fe-menu navbar-toggler-icon"></i>
          </button>
          <div className="navbar-slide bg-white ml-lg-4" id="navbarSupportedContent">
            <a href="#" className="btn toggle-sidebar d-lg-none text-muted ml-2 mt-3" data-toggle="toggle">
              <i className="fe fe-x"><span className="sr-only"></span></i>
            </a>
            
          </div>
      
          <ul className="navbar-nav d-flex flex-row">
            <li className="nav-item">
              <a className="nav-link text-muted my-2" href="./#" id="modeSwitcher" data-mode="light">
                <i className="fe fe-sun fe-16"></i>
              </a>
            </li>
            
            
          </ul>
        </div>
      </nav>

     
 <main role="main" className="main-content">
        <div className="container-fluid">

          
          {children}
         
        </div> 

        
        
  </main> 

      
  </div> 

  
  </div>
</>
  );
}
